# Generated by Django 6.0.7 on 2026-07-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='descripton',
            new_name='description',
        ),
    ]
